[profile.default]
bytecode_size_limit = 100_000
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path  = 'cache_forge'
solc = "0.8.26"  # 确保使用支持 cancun 的版本
evm_version = "cancun"
optimizer_runs = 1_000_000
via_ir = true
ffi = true
bytecode_hash = "none"
cbor_metadata = false
fs_permissions = [
    { access = "read-write", path = ".forge-snapshots/" },
    { access = "read", path = "./foundry-out" },
    { access = "read", path = "./script/config" },
    { access = "read", path = "./test/pool-cl/bin" },
    { access = "read", path = "./test/bin" },
]
gas_limit = "300000000"

remappings = [
    'pancake-create3-factory/=lib/pancake-create3-factory/',
    'src/=contracts/',
    'v4-core/=lib/v4-core/',
    'v4-core/src/=lib/v4-core/contracts/',
    'ds-test/=lib/forge-std/lib/ds-test/src/',
    'forge-std/=lib/forge-std/src/',
    '@openzeppelin/=lib/openzeppelin-contracts/',
    'solmate/=lib/solmate/',
    'permit2/src=lib/sunswap-permit2/contracts'
]

# added due to v1.0 foundry
# ref: https://book.getfoundry.sh/guides/v1.0-migration#expect-revert-cheatcode-disabled-on-internal-calls-by-default
allow_internal_expect_revert = true

additional_compiler_profiles = [
  { name = "clPosm", optimizer_runs = 9000 }
]

compilation_restrictions = [
  { paths = "src/pool-cl/CLPositionManager.sol", optimizer_runs = 9000 }
]

[fuzz]
runs = 5 # change this for higher number of fuzz runs locally

[profile.ci.fuzz]
runs = 10000

[invariant]
runs = 5 # change this for higher number of invariant runs locally
depth = 5 # default is 500: https://github.com/foundry-rs/foundry/pull/7957

[profile.ci.invariant]
runs = 100             # The number of calls to make in the invariant tests

[profile.ci_main.fuzz]
runs = 1000

[profile.ci_main.invariant]
runs = 1000           # The number of calls to make in the invariant tests
